robot_controller:
  ros__parameters:
    odom_pose_covariance: [0.01, 0.0, 0.0, 0.0, 0.0, 0.0,
                           0.0, 0.01, 0.0, 0.0, 0.0, 0.0,
                           0.0, 0.0, 0.01, 0.0, 0.0, 0.0,
                           0.0, 0.0, 0.0, 0.01, 0.0, 0.0,
                           0.0, 0.0, 0.0, 0.0, 0.01, 0.0,
                           0.0, 0.0, 0.0, 0.0, 0.0, 0.01]